### ISSUE TITLE
Download hangs

### ISSUE THREAD

**Issue by snuup** [OvertureMaps/io-site#176]
### Description

Tried to download a miniminiminimal dataset via the "download visible" button. Download apparently starts but never ends.

### What browser are you seeing the problem on? What version are you running?

Firefox and Chrome

### The OS you're using

Windows

### Steps to reproduce

https://explore.overturemaps.org/#21.09/48.1991447/16.3509439

press download visible

### The browser URL at the time you encountered the bug

https://explore.overturemaps.org/#21.09/48.1991447/16.3509439

**Comment by Bonkles** [comment]
@snuup thanks for the report! We have a bunch of fixes and updates for the download code ready to drop imminently. 

If you wouldn't mind, please retry the same download at https://explore.overturemaps.org/canary#21.09/48.1991447/16.3509439  

The 'canary' build is brand new and the link appears to work for me when I click download. 


(For internal folks - the error that the current version of the site spits back when this download is clicked has something to do with heterogenous datasets not being able to be written, which is a known issue that got fixed in the code over the summer).

**Comment by Bonkles** [comment]
Issue should be closed now that we've gone GA!
